### ISSUE TITLE
Error reports

### ISSUE THREAD

**Issue by SunboX** [nextcloud/windows-universal#54]
# This is a general issue to track automated error reports

**Comment by SunboX** [comment]
```
[Type]:[System.Exception]
[ExceptionMessage]:[The text associated with this error code could not be found.

A connection with the server could not be established
]
[StackTrace]:[
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x49318f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x492acb
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at SharedLibrary!<BaseAddress>+0x36ef5f
   at NextcloudApp!<BaseAddress>+0x493447
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x401cbf
   at SharedLibrary!<BaseAddress>+0x3ce85f
]
[InnerException]:[]
[OccurrenceDate]:[2016-11-17 02:10:18 GMT]
[AppTotalRuns]:[3]
[AppRunsAfterLastUpdate]:[3]
[AppVersion]:[1.0.2.0]
[Culture]:[en-IE]
[DeviceManufacturer]:[MicrosoftMDG]
[DeviceModel]:[RM-1116_12732]
[DeviceHardwareVersion]:[4.0.3.]
[DeviceFirmwareVersion]:[01078.00053.16236.35005]
[DeviceId]:[37271e4d-5ae7-497a-411e-28bac5133f3f]
[OperatingSystem]:[WindowsPhone]
[OSVersion]:[10.0.14393.448]
[Architecture]:[Arm]
[NetworkType]:[eduroam]
[FriendlyName]:[TE Windows phone]
[DeviceTotalMemory(Mb)]:[1536]
[AppCurrentMemoryUsage(Mb)]:[17.89844]
[IsoStorageAvailableSpaceLocal(Mb)]:[21110.92]
[IsoStorageAvailableSpaceTemporary(Mb)]:[21110.92]
[IsoStorageAvailableSpaceRoaming(Mb)]:[21110.92]
```

**Comment by SunboX** [comment]
```
[Type]:[System.Exception]
[ExceptionMessage]:[The text associated with this error code could not be found.

A connection with the server could not be established
]
[StackTrace]:[
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x49318f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x492acb
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at SharedLibrary!<BaseAddress>+0x36ef5f
   at NextcloudApp!<BaseAddress>+0x493447
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x401cbf
   at SharedLibrary!<BaseAddress>+0x3ce85f
]
[InnerException]:[]
[OccurrenceDate]:[2016-11-19 04:15:07 GMT]
[AppTotalRuns]:[5]
[AppRunsAfterLastUpdate]:[5]
[AppVersion]:[1.0.2.0]
[Culture]:[de-DE]
[DeviceManufacturer]:[MicrosoftMDG]
[DeviceModel]:[RM-1104_11210]
[DeviceHardwareVersion]:[2.1.1.]
[DeviceFirmwareVersion]:[01078.00053.16236.35035]
[DeviceId]:[37271e4d-5ae7-497a-411e-28bac5133f3f]
[OperatingSystem]:[WindowsPhone]
[OSVersion]:[10.0.14393.448]
[Architecture]:[Arm]
[NetworkType]:[WLAN-F89514]
[FriendlyName]:[Windows phone]
[DeviceTotalMemory(Mb)]:[1536]
[AppCurrentMemoryUsage(Mb)]:[17,46484]
[IsoStorageAvailableSpaceLocal(Mb)]:[8825,875]
[IsoStorageAvailableSpaceTemporary(Mb)]:[8825,875]
[IsoStorageAvailableSpaceRoaming(Mb)]:[8825,875]
```

**Comment by SunboX** [comment]
```
[Type]:[System.NullReferenceException]
[ExceptionMessage]:[Invalid pointer

Arg_NullReferenceException]
[StackTrace]:[
   at SharedLibrary!<BaseAddress>+0x3fb047
   at SharedLibrary!<BaseAddress>+0x555bbd
   at SharedLibrary!<BaseAddress>+0x38f6ad
   at SharedLibrary!<BaseAddress>+0x3ce705
   at SharedLibrary!<BaseAddress>+0x3c8425
   at System.Action.Invoke()
   at Prism.Mvvm.BindableBase.OnPropertyChanged(String propertyName)
   at NextcloudApp!<BaseAddress>+0x3ea3e9
   at NextcloudApp.ViewModels.MenuViewModel.set_User(Types.User value)
   at NextcloudApp!<BaseAddress>+0x491ae5
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x401cbf
   at SharedLibrary!<BaseAddress>+0x3ce85f
]
[InnerException]:[]
[OccurrenceDate]:[2016-11-23 01:48:42 GMT]
[AppTotalRuns]:[1]
[AppRunsAfterLastUpdate]:[1]
[AppVersion]:[1.0.3.0]
[Culture]:[de-CH]
[DeviceManufacturer]:[NOKIA]
[DeviceModel]:[RM-1077_1012]
[DeviceHardwareVersion]:[2.1.2.]
[DeviceFirmwareVersion]:[02177.00000.15184.36002]
[DeviceId]:[37271e4d-5ae7-497a-411e-28bac5133f3f]
[OperatingSystem]:[WindowsPhone]
[OSVersion]:[10.0.14393.448]
[Architecture]:[Arm]
[NetworkType]:[eth]
[FriendlyName]:[Umbis_Phone]
[DeviceTotalMemory(Mb)]:[390]
[AppCurrentMemoryUsage(Mb)]:[20.21094]
[IsoStorageAvailableSpaceLocal(Mb)]:[23082.03]
[IsoStorageAvailableSpaceTemporary(Mb)]:[23082.03]
[IsoStorageAvailableSpaceRoaming(Mb)]:[23082.03]
```

**Comment by SunboX** [comment]
```
[Type]:[System.Exception]
[ExceptionMessage]:[Excep_FromHResult 0x80072EFF]
[StackTrace]:[
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x49bcf9
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x49bab1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x49b5f9
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x401cbf
   at SharedLibrary!<BaseAddress>+0x3ce85f
]
[InnerException]:[]
[OccurrenceDate]:[2016-11-23 06:50:39 GMT]
[AppTotalRuns]:[2]
[AppRunsAfterLastUpdate]:[2]
[AppVersion]:[1.0.3.0]
[Culture]:[de-DE]
[DeviceManufacturer]:[MicrosoftMDG]
[DeviceModel]:[RM-1118_13880]
[DeviceHardwareVersion]:[2.1.6.]
[DeviceFirmwareVersion]:[01078.00053.16236.35026]
[DeviceId]:[37271e4d-5ae7-497a-411e-28bac5133f3f]
[OperatingSystem]:[WindowsPhone]
[OSVersion]:[10.0.14965.1001]
[Architecture]:[Arm]
[NetworkType]:[LangeNet]
[FriendlyName]:[surface phone]
[DeviceTotalMemory(Mb)]:[1536]
[AppCurrentMemoryUsage(Mb)]:[33,00391]
[IsoStorageAvailableSpaceLocal(Mb)]:[14149,89]
[IsoStorageAvailableSpaceTemporary(Mb)]:[14149,89]
[IsoStorageAvailableSpaceRoaming(Mb)]:[14149,89]
```

**Comment by SunboX** [comment]
```
[Type]:[System.Exception]
[ExceptionMessage]:[The group or resource is not in the correct state to perform the requested operation. (Excep_FromHResult 0x8007139F)]
[StackTrace]:[
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x499751
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x401cbf
   at SharedLibrary!<BaseAddress>+0x3ce85f
]
[InnerException]:[]
[OccurrenceDate]:[2016-11-25 07:48:54 GMT]
[AppTotalRuns]:[2]
[AppRunsAfterLastUpdate]:[2]
[AppVersion]:[1.0.3.0]
[Culture]:[de-DE]
[DeviceManufacturer]:[MicrosoftMDG]
[DeviceModel]:[RM-1154_15641]
[DeviceHardwareVersion]:[3.0.6.]
[DeviceFirmwareVersion]:[01078.00042.16352.50009]
[DeviceId]:[37271e4d-5ae7-497a-411e-28bac5133f3f]
[OperatingSystem]:[WindowsPhone]
[OSVersion]:[10.0.14393.448]
[Architecture]:[Arm]
[NetworkType]:[2B704BBE-6A95-41B7-B8D0-E49BEBD628BA]
[FriendlyName]:[Lumia 650]
[DeviceTotalMemory(Mb)]:[390]
[AppCurrentMemoryUsage(Mb)]:[15,52344]
[IsoStorageAvailableSpaceLocal(Mb)]:[49993,13]
[IsoStorageAvailableSpaceTemporary(Mb)]:[49993,13]
[IsoStorageAvailableSpaceRoaming(Mb)]:[49993,13]
```

**Comment by SunboX** [comment]
```
[Type]:[System.Exception]
[ExceptionMessage]:[The text associated with this error code could not be found.

A connection with the server could not be established
]
[StackTrace]:[
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x49bcf9
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x49bab1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x49b5f9
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x401cbf
   at SharedLibrary!<BaseAddress>+0x3ce85f
]
[InnerException]:[]
[OccurrenceDate]:[2016-11-25 10:17:56 GMT]
[AppTotalRuns]:[13]
[AppRunsAfterLastUpdate]:[13]
[AppVersion]:[1.0.3.0]
[Culture]:[de-DE]
[DeviceManufacturer]:[MicrosoftMDG]
[DeviceModel]:[RM-1085_11213]
[DeviceHardwareVersion]:[4.0.1.]
[DeviceFirmwareVersion]:[01078.00053.16236.35017]
[DeviceId]:[37271e4d-5ae7-497a-411e-28bac5133f3f]
[OperatingSystem]:[WindowsPhone]
[OSVersion]:[10.0.14393.448]
[Architecture]:[Arm]
[NetworkType]:[AAEA8DEE-FD80-4FBE-85B8-449B0965E77A]
[FriendlyName]:[Windows phone]
[DeviceTotalMemory(Mb)]:[1536]
[AppCurrentMemoryUsage(Mb)]:[21,14453]
[IsoStorageAvailableSpaceLocal(Mb)]:[28167,75]
[IsoStorageAvailableSpaceTemporary(Mb)]:[28167,75]
[IsoStorageAvailableSpaceRoaming(Mb)]:[28167,75]
```

**Comment by SunboX** [comment]
```
[Type]:[System.UnauthorizedAccessException]
[ExceptionMessage]:[Access is denied. (Excep_FromHResult 0x80070005)]
[StackTrace]:[
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x49b519
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x401cbf
   at SharedLibrary!<BaseAddress>+0x3ce85f
]
[InnerException]:[]
[OccurrenceDate]:[2016-11-27 06:50:50 GMT]
[AppTotalRuns]:[1]
[AppRunsAfterLastUpdate]:[1]
[AppVersion]:[1.0.3.0]
[Culture]:[de-DE]
[DeviceManufacturer]:[NOKIA]
[DeviceModel]:[RM-1040_1017]
[DeviceHardwareVersion]:[3.0.0.]
[DeviceFirmwareVersion]:[02040.00021.15235.53004]
[DeviceId]:[37271e4d-5ae7-497a-411e-28bac5133f3f]
[OperatingSystem]:[WindowsPhone]
[OSVersion]:[10.0.14393.448]
[Architecture]:[Arm]
[NetworkType]:[SCHANTALL TU MA WLAN]
[FriendlyName]:[Windows phone]
[DeviceTotalMemory(Mb)]:[390]
[AppCurrentMemoryUsage(Mb)]:[27,87891]
[IsoStorageAvailableSpaceLocal(Mb)]:[9588,781]
[IsoStorageAvailableSpaceTemporary(Mb)]:[9588,781]
[IsoStorageAvailableSpaceRoaming(Mb)]:[9588,781]
```

**Comment by SunboX** [comment]
```
[Type]:[System.Exception]
[ExceptionMessage]:[Xml_MissingRoot]
[StackTrace]:[
   at NextcloudApp!<BaseAddress>+0x3b25d7
   at NextcloudApp!<BaseAddress>+0x3b27bf
   at NextcloudApp!<BaseAddress>+0x561c5b
   at NextcloudApp!<BaseAddress>+0x561885
   at NextcloudApp!<BaseAddress>+0x3af887
   at NextcloudApp!<BaseAddress>+0x48fd09
   at NextcloudClient.NextcloudClient.GetFromMeta(String response, String elementName)
   at NextcloudClient.NextcloudClient.CheckOcsStatus(Web.Http.HttpResponseMessage response)
   at NextcloudApp!<BaseAddress>+0x492bab
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x49253b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x491ad1
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x401cbf
   at SharedLibrary!<BaseAddress>+0x3ce85f
]
[InnerException]:[]
[OccurrenceDate]:[2016-11-28 03:18:45 GMT]
[AppTotalRuns]:[1]
[AppRunsAfterLastUpdate]:[1]
[AppVersion]:[1.0.3.0]
[Culture]:[en-US]
[DeviceManufacturer]:[NOKIA]
[DeviceModel]:[RM-1072_1031]
[DeviceHardwareVersion]:[2.1.0.]
[DeviceFirmwareVersion]:[02177.00000.15184.36002]
[DeviceId]:[37271e4d-5ae7-497a-411e-28bac5133f3f]
[OperatingSystem]:[WindowsPhone]
[OSVersion]:[10.0.14965.1001]
[Architecture]:[Arm]
[NetworkType]:[H369AE0F741]
[FriendlyName]:[Windows phone]
[DeviceTotalMemory(Mb)]:[390]
[AppCurrentMemoryUsage(Mb)]:[16.02734]
[IsoStorageAvailableSpaceLocal(Mb)]:[1495.516]
[IsoStorageAvailableSpaceTemporary(Mb)]:[1495.516]
[IsoStorageAvailableSpaceRoaming(Mb)]:[1495.516]
```

**Comment by SunboX** [comment]
```
[Type]:[System.Exception]
[ExceptionMessage]:[Element not found.

Cannot get credential from Vault]
[StackTrace]:[
   at NextcloudApp!<BaseAddress>+0x3b123b
   at NextcloudApp!<BaseAddress>+0x3c48cd
   at NextcloudApp!<BaseAddress>+0x47fc9b
   at NextcloudApp.Services.ClientService.GetClient()
   at NextcloudApp!<BaseAddress>+0x49694d
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x401cbf
   at SharedLibrary!<BaseAddress>+0x3ce85f
]
[InnerException]:[]
[OccurrenceDate]:[2016-11-30 12:31:33 GMT]
[AppTotalRuns]:[2]
[AppRunsAfterLastUpdate]:[2]
[AppVersion]:[1.0.3.0]
[Culture]:[en-US]
[DeviceManufacturer]:[NOKIA]
[DeviceModel]:[RM-1031_1004]
[DeviceHardwareVersion]:[1.0.0.0]
[DeviceFirmwareVersion]:[02074.00000.15234.28003]
[DeviceId]:[37271e4d-5ae7-497a-411e-28bac5133f3f]
[OperatingSystem]:[WindowsPhone]
[OSVersion]:[10.0.14393.448]
[Architecture]:[Arm]
[NetworkType]:[HiTS]
[FriendlyName]:[hdcPhone]
[DeviceTotalMemory(Mb)]:[390]
[AppCurrentMemoryUsage(Mb)]:[13.28906]
[IsoStorageAvailableSpaceLocal(Mb)]:[4147.406]
[IsoStorageAvailableSpaceTemporary(Mb)]:[4147.406]
[IsoStorageAvailableSpaceRoaming(Mb)]:[4147.406]
```

**Comment by SunboX** [comment]
```
[Type]:[System.Exception]
[ExceptionMessage]:[Xml_MissingRoot]
[StackTrace]:[
   at NextcloudApp!<BaseAddress>+0x3b25d7
   at NextcloudApp!<BaseAddress>+0x3b27bf
   at NextcloudApp!<BaseAddress>+0x561ff3
   at NextcloudApp!<BaseAddress>+0x561c1d
   at NextcloudApp!<BaseAddress>+0x3af887
   at NextcloudApp!<BaseAddress>+0x48fd4d
   at NextcloudClient.NextcloudClient.GetFromMeta(String response, String elementName)
   at NextcloudClient.NextcloudClient.CheckOcsStatus(Web.Http.HttpResponseMessage response)
   at NextcloudApp!<BaseAddress>+0x49320b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x492b9b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x36fd1b
   at SharedLibrary!<BaseAddress>+0x36fbe9
   at SharedLibrary!<BaseAddress>+0x36fbb9
   at NextcloudApp!<BaseAddress>+0x492131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SharedLibrary!<BaseAddress>+0x401cbf
   at SharedLibrary!<BaseAddress>+0x3ce85f
]
[InnerException]:[]
[OccurrenceDate]:[2016-11-29 08:48:41 GMT]
[AppTotalRuns]:[9]
[AppRunsAfterLastUpdate]:[9]
[AppVersion]:[1.0.2.0]
[Culture]:[en-US]
[DeviceManufacturer]:[NOKIA]
[DeviceModel]:[RM-937_eu_belarus_russia_205]
[DeviceHardwareVersion]:[5.0.0.]
[DeviceFirmwareVersion]:[02540.00019.15053.26005]
[DeviceId]:[37271e4d-5ae7-497a-411e-28bac5133f3f]
[OperatingSystem]:[WindowsPhone]
[OSVersion]:[10.0.14393.448]
[Architecture]:[Arm]
[NetworkType]:[D-Link DIR 628 | Dom.ru | 478811]
[FriendlyName]:[Windows phone]
[DeviceTotalMemory(Mb)]:[900]
[AppCurrentMemoryUsage(Mb)]:[13.98438]
[IsoStorageAvailableSpaceLocal(Mb)]:[33648.38]
[IsoStorageAvailableSpaceTemporary(Mb)]:[33648.38]
[IsoStorageAvailableSpaceRoaming(Mb)]:[33648.38]
```
